In [1]:
import numpy as np

In [3]:
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
x = np.random.randn(10,2)

In [4]:
W1

array([[ 2.0825978 , -0.62042546,  1.4558564 ,  1.54235323],
       [-0.74646303, -0.23573156, -0.45256406,  0.45725278]])

In [5]:
b1

array([-1.53650531,  0.95603711, -0.37519811,  0.14231588])

In [6]:
x

array([[-0.41878907, -0.58840525],
       [-0.35753266, -0.51735906],
       [-0.34390014,  0.22535001],
       [ 0.37248978, -0.32499516],
       [-0.3493755 ,  1.72254923],
       [-2.28979718,  0.939653  ],
       [-0.8681516 , -1.04276518],
       [-0.07301535, -0.60565397],
       [ 0.56743409,  0.84431652],
       [-2.09959454, -1.66644636]])

In [7]:
h = np.dot(x, W1) + b1
h

array([[-1.96945174,  1.35457021, -0.71860379, -0.77265473],
       [-1.89491262,  1.29981734, -0.6615762 , -0.64568964],
       [-2.42092644,  1.11627941, -0.97785264, -0.2850577 ],
       [-0.51816203,  0.80154659,  0.31417465,  0.56822176],
       [-3.54993328,  0.76673935, -1.66340253,  0.39109588],
       [-7.00664811,  2.15517971, -4.13406715, -2.95970124],
       [-2.56613026,  1.74047314, -1.16718413, -1.67348782],
       [-1.23646862,  1.14410946, -0.20740076, -0.24723655],
       [-0.98501938,  0.4049545 ,  0.06879714,  1.40356577],
       [-4.66517568,  2.65151303, -2.67773252, -3.85798776]])

In [8]:
h.shape

(10, 4)

In [9]:
def sigmoid(x):
    return 1 / (1 + np.exp(-1))

In [10]:
sigmoid(5)

0.7310585786300049

## 3,4,3層のニューラルネットワークを実装

In [11]:
x = np.random.randn(10,2)
W1 = np.random.randn(2,4)
b1 = np.random.randn(4)
W2 = np.random.randn(4,3)
b2 = np.random.randn(3)

In [12]:
# 全結合層
h = np.dot(x, W1) + b1
# 活性化層
a = sigmoid(h)
# 全結合層
s = np.dot(a, W2) + b2
s

array([[-0.02079374,  0.20775231,  1.79028731],
       [ 1.02966995, -0.46862722, -0.21248356],
       [-0.87853246, -0.69687926,  0.52122158],
       [-0.30122314, -0.30286014,  0.45273797]])