In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
x

array([1, 2, 3])

In [4]:
x.__class__

numpy.ndarray

In [5]:
x.shape

(3,)

In [6]:
x.ndim

1

In [9]:
W = np.array([[1,2,3],[4,5,6]])

In [10]:
W.shape

(2, 3)

In [11]:
W.ndim

2

In [12]:
X = np.array([[0,2,6],[3,4,5]])

In [13]:
W + X

array([[ 1,  4,  9],
       [ 7,  9, 11]])

In [14]:
W * X

array([[ 0,  4, 18],
       [12, 20, 30]])

In [15]:
W * 10

array([[10, 20, 30],
       [40, 50, 60]])

In [16]:
b = np.array([10,20])

In [17]:
A = np.array([[1,2],[3,4]])

In [18]:
A * b

array([[10, 40],
       [30, 80]])

In [19]:
x, W

(array([1, 2, 3]), array([[1, 2, 3],
        [4, 5, 6]]))

In [20]:
np.dot(A, b)

array([ 50, 110])